spring:
   profiles:
   active:
   - dev

---
spring:
   profiles: dev #开发环境
   active:
	name:microservicecloud-config-xingyu-dev

---
spring:
   profiles: test #开发环境
   active:
	name:microservicecloud-config-xingyu-test